Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectDeliverable2.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Login()
        {
            return View();
        }

        [Route("register", Name = "Register")]
        public ActionResult Register()
        {
            return View();
        }
    }
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectDeliverable2.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }

        public ActionResult Diseases()
        {
            return View();
        }

        public ActionResult InfectiousDiseases()
        {
            return View();
        }


        public ActionResult HepatitisA()
        {
            return View();
        }

        public ActionResult HealthCentres()
        {
            return View();
        }

        public ActionResult Allergy()
        {
            return View();
        }


        public ActionResult FoodAllergy()
        {
            return View();
        }

        public ActionResult Specialist()
        {
            return View();
        }

        public ActionResult DietRecommendation()
        {
            return View();
        }

        public ActionResult ReportOne()
        {
            return View();
        }

        public ActionResult ReportTwo()
        {
            return View();
        }






    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectDeliverable2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Dashboard/Allergy.cshtml
@{
    ViewBag.Title = "Allergy";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<div align="center">
    <h1>Allergies</h1>
</div>

<br />

<div>
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:40%" onclick="location.href='@Url.Action("FoodAllergy","Dashboard")'">
            <h3> Food Allergies</h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3>Dust allergies</h3>
        </button>

    </div>
    <br />
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue;height:200px; width:40%">
            <h3> Skin Allergy</h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3>Animal allergies</h3>
        </button>

    </div>
    <br />
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue;height:200px; width:40%">
            <h3> Abnormal Allegies</h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3>Allergies</h3>
        </button>

    </div>
    <br />
</div>

Views/Dashboard/DietRecommendation.cshtml
@{
    ViewBag.Title = "DietRecommendation";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<h2 align="center"> Diet Recommendation </h2>

<div class="container">

    <label> Problem Type: </label>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            Select Problem Type
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#">Disease</a></li>
            <li><a href="#">Allergy</a></li>
        </ul>
    </div> <br />

    <label> Problem Category: </label>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            Select Problem Category Type
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#">Hepatitis A</a></li>
            <li><a href="#">Dust Allergy</a></li>
        </ul>
    </div> <br />

    <button class="btn" type="button"> SUBMIT </button> <br /> <br />

    <label> Diet Recommendation: </label> <br />
    <textarea rows="5" cols="60" name="txtHealthProblem">
        Enter problem here
    </textarea>

</div>

Views/Dashboard/Diseases.cshtml
@{
    ViewBag.Title = "diseases";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Frequently searched items</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>

<div class="row justify-content-center" style="height:5rem">
    <div class="col-md-6">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="https://images.unsplash.com/photo-1505751172876-fa1923c5c528?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Disease Name</h5>
                        <p>Short description here</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://images.unsplash.com/photo-1538108149393-fbbd81895907?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Disease Name</h5>
                        <p>Short description here</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://images.unsplash.com/photo-1542884748-2b87b36c6b90?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Disease Name</h5>
                        <p>Short description here</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Categories</h1>
    </div>

<div class="row justify-content-around">

    <button class="col-4" style="color:white; background-color:dodgerblue;height:200px; width:40%" onclick="location.href='@Url.Action("InfectiousDiseases","Dashboard")'">
        <h3> Infectious Diseases </h3>

    </button>

    <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
        <h3>Hereditary</h3>
    </button>

</div>

Views/Dashboard/FoodAllergy.cshtml
@{
    ViewBag.Title = "FoodAllergy";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<h2 align="center">Food Allergy</h2>

<div class="container">
    <div>
        <div>
            <p>Food allergies are estimated to affect 4% – 6% of children and 4% of adults, according to the Centers for Disease Control and Prevention. Food allergy symptoms are most common in babies and children, but they can appear at any age. You can even develop an allergy to foods you have eaten for years with no problems. SEE MORE</p>
        </div> <br />

        <div class="container">
            <div class="row justify-content-around">

                <div class="col-4" style="color:white;background-color:dodgerblue;height:300px; width:40%" align="cen">
                    <h3> Symptoms</h3>
                    <ul>
                        <li>Fatigue</li>
                        <li>Fatigue</li>
                        <li>Fatigue</li>
                    </ul>
                </div>

                <div class="col-4" style="color:white;background-color:dodgerblue; height:300px; width:40%">
                    <h3>Recommended Remedies</h3>
                </div>
            </div>
            <br />

            <br />
            <br />

            <div class="row justify-content-around">
                <div class="col-md-4" style="color:white; background-color:dodgerblue;height:300px; width:40%">
                    This is a rectangle!
                </div>


                <div class="col-md-4">
                    <button type="button" class="btn btn-info active" role="button" aria-pressed="true" onclick="location.href='@Url.Action("Specialist","Dashboard")'" >Contact Specialist</button>

                    <br />
                    <br />

                    <button type="button" class="btn btn-info active" role="button" aria-pressed="true" onclick="location.href='@Url.Action("DietRecommendation","Dashboard")'" >Recommended Diet</button>

                </div>
            </div>
        </div>

        <div align="right" >
            <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" onclick="location.href='@Url.Action("Allergy","Dashboard")'">
                Back
            </button>
        </div>

Views/Dashboard/HepatitisA.cshtml
@{
    ViewBag.Title = "HepatitisA";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<div align="center">
    <h1>HepatitisA</h1>
    <h5>Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus. The virus is one of several types of hepatitis viruses that cause inflammation and affect your liver's ability to function. SEE MORE</h5>
</div>
<br />

<br />
<div class="container">
    <div class="row justify-content-around">

        <div class="col-4" style="color:white;background-color:dodgerblue;height:300px; width:40%" align="cen">
            <h3> Symptoms</h3>
            <ul>
                <li>Fatigue</li>
                <li>Fatigue</li>
                <li>Fatigue</li>
            </ul>
        </div>

        <div class="col-4" style="color:white;background-color:dodgerblue; height:300px; width:40%">
            <h3>Recommended Remedies</h3>
        </div>
    </div>
    <br />

    <br />
    <br />

    <div class="row justify-content-around">
        <div class="col-md-4" style="color:white; background-color:dodgerblue;height:300px; width:40%">
            This is a rectangle!
        </div>


        <div class="col-md-4">
            <button type="button" class="btn btn-info active" role="button" aria-pressed="true" onclick="location.href='@Url.Action("Specialist","Dashboard")'" >Contact Specialist</button>

            <br />
            <br />

            <button type="button" class="btn btn-info active" role="button" aria-pressed="true" onclick="location.href='@Url.Action("DietRecommendation","Dashboard")'" >Recommended Diet</button>

        </div>
    </div>
</div>

<div align="right">
    <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" onclick="location.href='@Url.Action("Allergy","Dashboard")'">
        Back
    </button>
</div>

Views/Dashboard/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h3 class="h3 mb-0 text-gray-800">Your IBEE Stats</h3>
        <button href="#" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm" onclick="location.href='@Url.Action("ReportOne","Dashboard")'"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report 1</button>
        <button href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"onclick="location.href='@Url.Action("ReportTwo","Dashboard")'"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report 2</button>
    </div>

<!-- Content Row -->
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Doctor's visits</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">current dietary preferences</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">content consumed</div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Reports generated</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Content Row -->
<!-- Content Row -->
<div class="row">

    <!-- Content Column -->
    <div class="col-lg-6 mb-4">

        <!-- Project Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Recommended reads based on your profile</h6>
            </div>
            <div class="card-body">
                <h4 class="small font-weight-bold">Diet recommendation 1<span class="float-right">20%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Case study 1 <span class="float-right">40%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Disease 1 <span class="float-right">60%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Health Article 1 <span class="float-right">80%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-6 mb-4">

        <!-- Illustrations -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Featured Article</h6>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
                </div>
                <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://eddicus.com/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                <a target="_blank" rel="nofollow" href="https://eddicus.com/">Find out more &rarr;</a>
            </div>
        </div>

    </div>
</div>

Views/Dashboard/InfectiousDiseases.cshtml
@{
    ViewBag.Title = "InfectiousDiseases";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<div align="center">
    <h1>Infectious Diseases</h1>
</div>

<br />

<div>
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:40%" onclick="location.href='@Url.Action("HepatitisA","Dashboard")'">
            <h3> Hepatitis A </h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3> Ebola </h3>
        </button>

    </div>
    <br />
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue;height:200px; width:40%">
            <h3> Listeria </h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3>Cellulitis</h3>
        </button>

    </div>
    <br />
    <div class="row justify-content-around">

        <button class="col-4" style="color:white; background-color:dodgerblue;height:200px; width:40%">
            <h3> Pneumonia</h3>

        </button>

        <button class="col-4" style="color:white; background-color:dodgerblue; height:200px; width:50px">
            <h3>Strep throat</h3>
        </button>

    </div>
    <br />
</div>

Views/Dashboard/Profile.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Dashboard/Index.cshtml";
}


<div class="container">
    <h1>Profile of Shaun Mabena</h1>
    <hr>
    <div class="row">
        <!-- left column -->
        <div class="col-md-3">
            <div class="text-center">
                <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                <h6>Upload a different photo...</h6>

                <input type="file" class="form-control">
            </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <div class="alert alert-info alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a>
                <i class="fa fa-coffee"></i>
                Edit your information            
             </div>
            <h3>Personal info</h3>

            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <label class="col-lg-3 control-label">First name:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value="Shaun">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Surname</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value="Mabena">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Email:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value=" ">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 control-label">Height    :</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value=" ">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Weight:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value=" ">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Allergies:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" value=" ">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Province:</label>
                    <div class="col-lg-8">
                        <div class="ui-select">
                            <select id="user_time_zone" class="form-control">
                                <option value="E">Eastern Cape</option>
                                <option value="FS">Free State </option>
                                <option value="G">Gauteng</option>
                                <option value="KwaZulu-Natal">KwaZulu-Natal</option>
                                <option value="LMP">Limpopo</option>
                                <option value="MP" selected="selected">Mpumalanga</option>
                                <option value="NC">Northern Cape</option>
                                <option value="NW">North West</option>
                                <option value="WC">Western Cape</option>

                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">City</label>
                    <div class="col-lg-8">
                        <div class="ui-select">
                            <select id="user_time_zone" class="form-control">
                                <option value="E">Benoni</option>
                                <option value="FS">Boksburg</option>
                                <option value="G">Brakpan</option>
                                <option value="KwaZulu-Natal">Carletonville</option>
                                <option value="LMP">Germiston</option>
                                <option value="MP" selected="selected">Johannesburg</option>
                                <option value="NC">Pretoria</option>
                                <option value="NW">Randburg</option>
                                <option value="WC">Randfontein</option>
                                <option value="WC">Roodepoort</option>
                                <option value="WC">Soweto</option>
                                <option value="WC">Vanderbijlpark</option>
                                <option value="WC">Vereeniging</option>

                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <input type="button" class="btn btn-primary" value="Save Changes">
                        <span></span>
                        <input type="button" class="btn btn-default" onclick="location.href='@Url.Action("Home","Dashboard")'"  value="Cancel">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<hr>

Views/Dashboard/ReportOne.cshtml
@{
    ViewBag.Title = "ReportOne";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<h2 align="center" >ReportOne</h2>

<button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" onclick="location.href='@Url.Action("Home","Dashboard")'" > BACK </button>



<div style="border:double; background-color:antiquewhite">

    <img src="~/Content/Capture.GIF" alt="Italian Trulli" style="width:80%">
</div>

<button>
    <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" href="~/Content/Report1.pdf">Download Report</a>
</button>

Views/Dashboard/ReportTwo.cshtml
@{
    ViewBag.Title = "ReportTwo";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<h2 align="center">ReportTwo</h2>

<button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" onclick="location.href='@Url.Action("Home","Dashboard")'"> BACK </button>

<div style="border:double; background-color:antiquewhite">

    <img src="~/Content/Capture2.GIF" alt="Italian Trulli" style="width:80%">
</div>

<button>
    <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" href="~/Content/Report2.pdf">Download Report</a>
</button>

Views/Dashboard/Specialist.cshtml
@{
    ViewBag.Title = "Specialist";
    Layout = "~/Views/Dashboard/Index.cshtml";
}

<h2 align="center"> Dr Viktor Vaughn Doom </h2>

<div class="container">

    <label> Health Problem Type: </label>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            Select Health Problem
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#">Food Allergy</a></li>
            <li><a href="#">Dust Allergy</a></li>
            <li><a href="#">Skin Allergy</a></li>
        </ul>
    </div> <br />

    <label> Health Problem: </label> <br />
    <textarea rows="5" cols="60" name="txtHealthProblem">
        Enter problem here
    </textarea> <br /> <br />

    <button class="btn" type="button"> SUBMIT </button>

</div>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="@Url.RouteUrl("welcome")">
            <img src="@Url.Content("~/Content/ibee.png")" style="height:46px;width:66px;" alt="Alternate Text" />
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="@Url.RouteUrl("about")">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="@Url.RouteUrl("contact")">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="@Url.RouteUrl("register")">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="@Url.RouteUrl("login")">Login</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<section id="about" class="about-section text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2 class="text-white mb-4">About IBEE Health</h2>
                <p class="text-white-50">
                    IBEEHealth aims to be an informative and interactive platform where health and well-being matters are articulated. We aim to produce expert information to the users to ensure that their knowledge regarding health issues is enhanced. Our vision is in line with the United Nations development goal- Good health and Well-Being, to ensure that lack of knowledge in South Africa and Africa as whole is tackled with immense results.

                    Vision: Our focus is to advocate and equip people regarding health issues to ensure reduction of insufficient information and knowledge.
                    Mission: Our mission is to fortify availability to easily accessible information.
</p>
            </div>
        </div>
        <img src="img/ipad.png" class="img-fluid" alt="">
    </div>
</section>

<footer class="bg-black small text-center text-white-50">
    <div class="container">
        Copyright &copy; IBEEHEALTH 2019
    </div>
</footer>